#spring:
#  application:
#    name: api-gateway
#
#server:
#  port: 7000
#
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
##      defaultZone: http://host:docker.internal:8761/eureka/
##      defaultZone: http://maksymiths/register-service:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/
##      defaultZone: http://13.48.248.158:5555/eureka/
#  instance:
##    hostname: register-service
#    hostname: localhost
#
#
#ribbon:
#  eureka:
#    enabled: true
#
#hystrix:
#  metrics:
#    polling-interval-ms: 50000000
#
#
#
#zuul:
#  prefix: /api
#  routes:
#    video-data:
#      path=/video-data/**
#      service-id=video-data
#      stripPrefix:true
#    temp001:
#      path=/temp001/**
#      service-id=temp001
#      stripPrefix:true
#
